language: node_js
node_js:
    - '8'
dist: trusty
sudo: required
services:
- mysql
addons:
  chrome: stable
  firefox: latest
env:
    - EMONCMS_REPO="https://github.com/emoncms/emoncms.git" EMONCMS_BRANCH="stable"
    - secure: "M1RwV/RbAfRvv2s6vQlEGVYYV00CGLQ4xQ6eObIOp7dgrUwguRh0f5mJCC60BR5eFCgOE7YZSL+4rps0v8GPbO+/UPUrOzBST3mTbD05deXElQmFy6nNsvWjIxlIVLwSgwsOuMo9pCE6mu8VvLetj7SsRw/yipY3W8ibH9Xc4/A9aUeU8N71Skd5VCrqsshKZjLWkye2Cwgk5UAVGltsdPxKDu1kEGMBhLU4AgKw7KWhB3HwcxOVb74GZ7BHzM92Q94/Dm+26SecRqQ07x1WTSyUbzu+2iFmbGAQhyOFBm+/Jzw0fnqRqXpQZH5a6+ElhaTGYQSkA3k5ER2NQlx3Wnopr38fVj9IUCraMXgIp/7t+JoN2JkdQFCJdXHR+gnGhp+lLPz2sT3pfmpcYDNIxGxoSlix/7a8dYxnk+iOpgAQbR/JQQp4CmB9WbFPavar8m9YtkvGsKvKbivG1eXS2Y3hFOam3+Wzii5qw73VJXDbjylSABLnjYk+TDk0O0kowv9kaHMq1p0n8FuL47BLEgcZuW7FICLEZ+zQ+e9LWLxHAIK0QgqQFB02rP/YOUQCq8MvEpGHQhesn9WnMUBGE7CDCfGlCYbxMEhBKhsOfylwQs3G4BdXW5ZeMPCJRP1fmp9K5U1GnDx2H2k6hYwaNNYShbk6YT0GTtqmNPCDdHs="
before_install:
    # Install Apache + PHP - adapted from https://docs.travis-ci.com/user/languages/php/
    - sudo apt-get update
    - sudo apt-get install apache2 libapache2-mod-fastcgi -y
    ## enable php-fpm
    - sudo cp ~/.phpenv/versions/5.6/etc/php-fpm.conf.default ~/.phpenv/versions/5.6/etc/php-fpm.conf
    - sudo a2enmod rewrite actions fastcgi alias
    - echo "cgi.fix_pathinfo = 1" >> ~/.phpenv/versions/5.6/etc/php.ini
    - sudo sed -i -e "s,www-data,travis,g" /etc/apache2/envvars
    - sudo chown -R travis:travis /var/lib/apache2/fastcgi
    - "~/.phpenv/versions/5.6/sbin/php-fpm"
    ## configure apache virtual hosts
    - sudo cp -f travis-CI/travis-ci-apache /etc/apache2/sites-available/000-default.conf
    - sudo service apache2 restart
       
install:
    # Install emonCMS - adapted from https://github.com/emoncms/emoncms/blob/master/docs/LinuxInstall.md
    ## Setup in apache
    - sudo apt-get install php-pear redis-server build-essential php5-dev g++ wget -y
    - sudo pear channel-discover pear.swiftmailer.org
    - printf "\n" | sudo pecl install swift/swift redis
    - printf "extension=redis.so" | sudo tee /etc/php5/mods-available/redis.ini 1>&2
    - sudo php5enmod redis
    - sudo cp ./travis-CI/emoncms.conf /etc/apache2/sites-available/emoncms.conf
    - sudo a2ensite emoncms
    - sudo service apache2 reload
    - cd /var/www/
    - sudo chown $USER html
    ## Clone emonCMS
    - cd html
    - git clone --depth=50 -b $EMONCMS_BRANCH $EMONCMS_REPO
    - cd /var/www/html/emoncms
    - git pull
    ## Setup database and feeds
    - mysql -e 'CREATE DATABASE IF NOT EXISTS emoncms DEFAULT CHARACTER SET utf8;'
    - sudo mkdir /var/lib/phpfiwa
    - sudo mkdir /var/lib/phpfina
    - sudo mkdir /var/lib/phptimeseries
    - sudo chown www-data:root /var/lib/phpfiwa
    - sudo chown www-data:root /var/lib/phpfina
    - sudo chown www-data:root /var/lib/phptimeseries
    ## Create settings.php
    - cd /var/www/html/emoncms/
    - cp default.settings.php settings.php
    - sed -i 's/_DB_USER_/travis/g' settings.php
    - sed -i 's/_DB_PASSWORD_//g' settings.php
    - sed -i 's/$enable_multi_user = false;/$enable_multi_user = true;/g' settings.php
    ### Not setting up SMTP - needs to be done if we want to test emails features
    ## Install MHEP theme
    - cd /var/www/html/emoncms/Theme
    - git clone --depth=50 https://github.com/carboncoop/MHEP_theme.git CCoop
    - cd /var/www/html/emoncms/
    - sed -i 's/$theme = "basic";/$theme = "CCoop";/g' settings.php
    ## Install MHEP
    - cd /var/www/html/emoncms/Modules
    - git clone --depth=50 --branch=$TRAVIS_BRANCH https://github.com/$TRAVIS_REPO_SLUG assessment
    - cd assessment
    - git submodule update --init --recursive
    ## Setup test suite
    - cd /var/www/html/emoncms/Modules/assessment/tests
    - npm install
    - "./node_modules/.bin/selenium-standalone install"
    - "./node_modules/.bin/selenium-standalone start > /dev/null 2>&1 &"
    - mkdir webdrivers
    - cd webdrivers
    - wget https://chromedriver.storage.googleapis.com/2.42/chromedriver_linux64.zip
    - unzip chromedriver_linux64.zip
    - sudo chmod +x chromedriver
    - wget https://github.com/mozilla/geckodriver/releases/download/v0.22.0/geckodriver-v0.22.0-linux64.tar.gz
    - tar -xvzf geckodriver-v0.22.0-linux64.tar.gz
    - sudo chmod +x geckodriver
    - export PATH=$PATH:/var/www/html/emoncms/Modules/assessment/tests/webdrivers
script:
    - curl -vL http://127.0.0.1/emoncms
    - cd /var/www/html/emoncms/Modules/assessment/tests
    - HEADLESS=true ./node_modules/.bin/wdio wdio.conf.js --spec travis_specs/emonCMS-setup.js
    - HEADLESS=true DEBUG=true TRAVIS=true ./node_modules/.bin/wdio wdio.conf.js
after_success:
    # SSH setup for deployment
    - cd /var/www/html/emoncms/Modules/assessment/
    - openssl aes-256-cbc -K $encrypted_d561feca5f1b_key -iv $encrypted_d561feca5f1b_iv -in deploy_key.enc -out ./deploy_key -d
    - ssh-add ./deploy_key
    - eval "$(ssh-agent -s)"
    - chmod 600 ./deploy_key
    - echo -e "Host $PRODUCTION_SERVER\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
    - ssh -i ./deploy_key deploy@$PRODUCTION_SERVER
    - sh deployer.sh 
